const {chromium}=require('../.qa/node_modules/playwright');
const assert=require('assert'),fs=require('fs');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],requests=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/api/health',r=>r.fulfill({json:{opencv:'5.0.0',model:'fixture.onnx'}}));
  await page.route('**/api/ortho',r=>r.fulfill({json:{image:'data:image/png;base64,'+fs.readFileSync('.qa/sample.png').toString('base64'),bbox:[0,0,1000,1000],meters_per_pixel:1}}));
  const section=(a,b)=>({path:[a,b],uncertain:true,low_fraction:.8,confidence:.2});
  await page.route('**/api/wololo',r=>{
   const data=r.request().postDataJSON();requests.push(data);
   const p=data.points;
   return r.fulfill({json:{sections:p.length===3?[section(p[0],p[1]),section(p[1],p[2])]:[section(p[0],[.2,.5]),section([.2,.5],[.4,.5]),section([.4,.5],p[1])],diagnostics:{tiles:9,computed_tiles:requests.length===1?9:0}}});
  });
  await page.goto('http://127.0.0.1:5000');
  assert.deepEqual(await page.locator('#mode option').evaluateAll(items=>items.map(i=>i.value)),['segmentation','automatic','wololo']);
  await page.locator('#load').click();await page.locator('#ortho-loader').waitFor({state:'hidden'});
  await page.locator('#mode').selectOption('wololo');
  const rect=await page.locator('#map').boundingBox();
  await page.locator('#map').focus();await page.keyboard.press('a');
  const marker=async x=>{const box=await page.locator('#map').boundingBox();const at=await page.evaluate(x=>[panX+x*1024*viewScale(),panY+.5*1024*viewScale()],x);await page.mouse.click(box.x+at[0],box.y+at[1]);};
  await marker(.1);
  await marker(.2);
  await marker(.8);
  assert.equal(await page.locator('#wololo-limit').inputValue(),'2300000');
  await page.locator('#wololo-limit').fill('1500000');
  assert.equal(await page.locator('#wololo-tolerance').inputValue(),'0.5');
  await page.locator('#wololo-tolerance').selectOption('2');
  assert(await page.locator('#threshold').isHidden());assert(await page.locator('#auto-detect').isHidden());
  await page.locator('#wololo-start').click();await page.locator('#wololo-review').waitFor({state:'visible'});
  assert.equal(requests[0].search_limit,1500000);
  assert.equal(requests[0].tolerance_m,2);
  assert.equal(await page.locator('#zoom-value').textContent(),'800%');
  assert.equal(await page.evaluate(()=>paths.length),0,'pending proposal must not be exported');
  await page.locator('#wololo-confirm').click();
  assert.deepEqual(await page.evaluate(()=>paths[0].at(-1)),requests[0].points[1]);
  await page.locator('#wololo-back').click();assert.equal(await page.evaluate(()=>paths.length),0);
  await page.locator('#wololo-confirm').click();
  await page.locator('#wololo-correct').click();
  await page.mouse.click(rect.x+rect.width*.5,rect.y+rect.height*.5);
  await page.waitForFunction(()=>!document.querySelector('#wololo-confirm').disabled);
  assert.equal(requests.length,2);assert.deepEqual(requests[1].points[0],requests[0].points[1]);assert.equal(requests[1].points.length,3);
  await page.locator('#wololo-confirm').click();
  await page.locator('#wololo-finish').click();
  assert(await page.locator('#wololo-review').isHidden());
  const line=await page.evaluate(()=>paths[0]);assert.deepEqual(line.at(-1),requests[1].points[1]);assert.notDeepEqual(line.at(-1),requests[1].points[2]);
  const download=page.waitForEvent('download');await page.locator('#export-osm').click();assert.equal((await download).suggestedFilename(),'caminos-pnoa.osm');
  await page.locator('#wololo-reset').click();assert.equal(await page.evaluate(()=>points.length),0);assert.equal(await page.evaluate(()=>paths.length),1);
  assert.equal(await page.locator('#tool').inputValue(),'correct');
  await page.locator('#zoom-reset').click();await page.locator('#map').focus();await page.keyboard.press('a');
  await marker(.15);await marker(.3);await marker(.7);
  assert.deepEqual(await page.evaluate(()=>pointIds),[1,2,3]);
  await page.locator('#wololo-start').click();await page.locator('#wololo-review').waitFor({state:'visible'});
  const sent=requests.at(-1).points;assert(sent[0][0]<sent[1][0]&&sent[1][0]<sent[2][0]);
  await page.locator('#wololo-confirm').click();await page.locator('#wololo-confirm').click();
  assert(await page.locator('#wololo-review').isHidden());assert.equal(await page.evaluate(()=>wololoState),null);
  assert.deepEqual(await page.evaluate(()=>paths.at(-1).at(-1)),sent[2]);assert.equal(requests.length,3,'completion must not request a reverse route');
  await page.locator('#wololo-reset').click();await page.locator('#zoom-reset').click();
  const outside=await page.evaluate(()=>[panX+.95*1024*viewScale(),panY+.05*1024*viewScale()]);
  const box=await page.locator('#map').boundingBox();await page.mouse.click(box.x+outside[0],box.y+outside[1]);
  const placed=await page.evaluate(()=>points[0]);assert(Math.abs(placed[0]-.95)<.002&&Math.abs(placed[1]-.05)<.002,'markers can be placed outside the previous corridor');
  await page.locator('#mode').selectOption('automatic');assert(await page.locator('#auto-detect').isVisible());assert(await page.locator('#wololo-panel').isHidden());
  assert(await page.locator('#threshold').isVisible());
  assert.deepEqual(errors,[]);console.log('Wololo GUI OK: markers, doubtful tile, confirm, undo, correction, finish and OSM export; existing modes retained.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
