const assert=require('assert');
const G=require('../static/trace-geometry');
const bbox=[0,0,1000,1000];
const line=[[.1,.1],[.2,.10001],[.3,.1],[.4,.3],[.5,.30001],[.6,.3]];
const simple=G.simplify(line,1,bbox);
assert(simple.length<line.length);
assert.deepEqual(simple[0],line[0]);assert.deepEqual(simple.at(-1),line.at(-1));
assert(simple.some(p=>p[0]===.4&&p[1]===.3));
const network=[line,[[.2,.10001],[.2,.3]]];
assert(G.simplify(line,10,bbox,G.sharedVertices(network)).some(p=>p[0]===.2));
const ring=[[.1,.1],[.2,.1],[.2,.2],[.1,.2],[.1,.1]];
const reducedRing=G.simplify(ring,10000,bbox);
assert.deepEqual(reducedRing[0],reducedRing.at(-1));assert(new Set(reducedRing.map(p=>p.join(','))).size>=3);
assert.throws(()=>G.simplify(line,NaN,bbox));
const features=network.map(path=>({type:'Feature',properties:{source:'PNOA & "IGN"'},geometry:{type:'LineString',coordinates:path.map(p=>G.coordinates(p,bbox))}}));
const xml=G.osm({type:'FeatureCollection',features});
assert(xml.includes('<osm version="0.6"'));assert(xml.includes('&amp; &quot;IGN&quot;'));
const nodes=[...xml.matchAll(/<node id="(-\d+)"/g)].map(m=>m[1]);
const refs=[...xml.matchAll(/<nd ref="(-\d+)"/g)].map(m=>m[1]);
assert(refs.every(ref=>nodes.includes(ref)));assert.equal(nodes.length,7);assert(refs.filter(ref=>ref===refs[1]).length===2);
assert(!xml.includes('highway'));assert(xml.includes('fixme'));assert(G.length(features[0].geometry.coordinates)>0);
assert.throws(()=>G.osm({features:[]}));
console.log('Geometry OK: meter tolerance, endpoints, shared junctions, closed loops and OSM node references.');
